[package]
name = "funlang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
pretty_assertions_sorted = "1.2.3"

[dependencies]
anyhow = "1.0.75"
colorful = "0.2.2"
pretty_assertions = "1.4.1"
